prometheus:
  port: 2112
  metrics: 
    edns_bufsiz: 
      aggregations: 
        EDNSBufSiz:
          type: Bucket
          params: 
            start: 511
            width: 512
            count: 9
            none_counter: true
            use_midpoint: true
    edns_version:
      aggregations: 
        EDNSVersion:
          type: Filter
          params: 
            "0": {}
            "none": {}
    idn_qname: {} 
    rd_bit: {} 
    do_bit: {} 
    rcode: {}
    qtype: {} 
    client_port_range: 
      aggregations: 
        PortRange:
          type: Bucket
          params: 
            start: 1023
            width: 1024
            count: 64 
            none_counter: true
            use_midpoint: true 
    qtype_vs_qnamelen: 
      aggregations: 
        QnameLen:
          type: Bucket
          params: 
            start: 3 
            width: 4
            count: 16
    rcode_vs_replylen:
      aggregations: 
        ReplyLen:
          type: Bucket
          params: 
            start: 31
            width: 32
            count: 40
    dns_ip_version_vs_qtype: {}
    direction_vs_ipproto: {} 
    transport_vs_qtype: {} 
    opcode: {}
    qtype_vs_tld: 
      aggregations: 
        TLD: 
          type: Filter
          params: 
            "de": {}
            "localhost": {}
    qr_aa_bits: {} 
    chaos_types_and_names:  
      aggregations: 
        Qname: 
          type: Filter
          params: 
            "hostname.bind": {}
            "version.bind": {}
    priming_responses:
      aggregations: 
        ReplyLen:
          type: Bucket
          params: 
            start: 31
            width: 32
            count: 40
    priming_queries:
      aggregations: 
        EDNSBufSiz:
          type: Bucket
          params: 
            start: 511
            width: 512
            count: 9
            none_counter: true
            use_midpoint: true
    pcap_stats: {} 

    # Not exported:
    # servfail_qname
    # second_ld_vs_rcode
    # third_ld_vs_rcode

    # idn_vs_tld: {} # Nicht im dsp
    # certain_qnames_vs_qtype

    # ipv6_rsn_abusers 
    # client_addr_vs_rcode:
    # client_subnet2
    # client_subnet

interval: 5s
data: /data/exporter_dsc
remove: false