on:
  push: {}

name: Test & Release

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: make test

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: go-test-converage
        path: cover.out
      
  build: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: make build-linux

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dscexporter
          path: ./build/linux/dscexporter

  upload-release-asset:
    needs: build
    name: Upload Release Asset
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: dscexporter
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dscexporter
            