# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on: 
  push: {}
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: make test

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: go-test-converage
        path: cover.out
      
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: make build-linux

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dscexporter
          path: ./build/linux/dscexporter